travis:
  secure:
    BINSTAR_TOKEN: Wwp05t0DtmCfsVWzJUNBqqrKsqZyalat/wkVqLQ1KMwYSWgSGd7G4pkvieONftmBEJ+ME8KhCwarTSkEVtn1xvogf9fXOg+0CAqQvvYSN5fZ+Vf7ZLlbAvzrUsw4sN1h6Xyhjo1MiennJQSbF9tbIlY5ggxj0ye+tGkGELsrh8pGKBtJUsejePCzLtF0+3UaHl1JPZXvybaCAok8baXF8IzL35Z0NRwwxHuNDhgCCFfqK3wQkV/G8mT3RtIOB6CvGNrZQZYK7jik7RdCy6/jRa0pcdXm0IoNBfRBpAqYjia44UdLhZI8nzsGBtyGkpACNVSxpJxidZ/6oPZQNzY36VtrmhFtyDC6yJqX7swv/sBoXtN8RY2H4yFVNH9ekDDYEDWMm+mta+wAYZwtEbRkh78P4yCbjFuvq82aQDiU1GzOWEoLFQEMwah0LZwhYzhbRDxD8twS8LVDQoMf6LvzsvH+GfVbjm1tIP8O0zM2bOmu73h9F4kaWg+wt8bl290anT5dM7cGSpN5BL73cjbPFG1IGfbaRYN3wj1ZFaIWawLcnTtphd5Dh60n/prueGSj3dNhw2n+YsNXFXnwLOTKu9eMpblFPVoxGlGbe1vODEpNjBLTtA0NWEhZ1oQ6AKyhib0A2zvavNpQRPX4GHtEwyfq753dkqgKkoKqc7vooCA=
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
